### ISSUE TITLE
Hausnummern Pflichtfeld

### ISSUE THREAD

**Issue by mira-miracoli** [TransDB-de/projektverwaltung#1]
## Der Vorschlag
Das Hausnummern-Feld als bedingtes Pflichtfeld, gekoppelt an einen eintrag im Feld "Strasse" einrichten.
Zusätzlich Straßenfeld auf Nummer am Ende prüfen.

## Grund für die Verbesserung
Oft werden die Hausnummern mit im Straßenfeld eingetragen und das Hausnummernfeld leer gelassen.
Das Geodaten System kann damit nicht umgehen und es fehlen für diesen Eintrag die Geodaten. Bisher müssen diese Einträge manuell korrigiert werden. Bei gefühlt 1/5 der Einträge mit diesem Problem ein wachsender Aufwand.

**Comment by ElectronicBlueberry** [comment]
Das Problem an der Pflichtfeld Lösung ist, das wir die Hausnummer bewusst optional lassen wollten. Ein Vorschlag von mir wäre das über einen Hinweis im Frontend zu lösen.

Wenn die Submission Form entdeckt dass das Straße Feld mit einer Zahl endet, kann es eine Warnung anzeigen welche das Feld Gelb markiert und darauf hinweist die Hausnummer separat einzutragen.

**Comment by fleaz** [comment]
> Wenn die Submission Form entdeckt, dass das Straße Feld mit einer Zahl endet

Zwei  Punkte die mir da gerade spontan zu einfallen: Es gibt Hausnummern mit Buchstaben (bspw. "4b" ), dann endet der String nicht mit einer Zahl, einfach nach einer Zahl im String suchen geht aber auch nicht immer gut da es Straßennamen mit Zahlen gibt (bspw: "Straße des 17. Juni").

**Comment by mira-miracoli** [comment]
Gibt es denn Adressen die nur aus einer Straße ohne Hausnummer bestehen?
Nach meiner Recherche ist eine Hausnummer verpflichtend und seltenen Ausnahmefällen wird in anderen Formularen einfach 1 angegeben.
Ich denke das bedingte Pflichtfeld wäre daher die am wenigsten fehleranfällige Lösung.

**Comment by ElectronicBlueberry** [comment]
Ich würde gerne ermöglicht viele edge-cases offen halten. Selbst wenn in DE Hausnummern garantiert sind (wobei ich mir dabei nicht sicher bin), muss das nicht fürs Ausland der Fall sein falls wir expandieren.

Zur Verdeutlichung des Vorschlags: Mir geht es dabei um einen Hinweis der einen nicht davon abhält den Eintrag einzureichen, sondern nur darauf hindeutet dass wir das Hausnummer Feld haben, um weniger fehlerhafte Einträge zu erhalten.

Das mit den Buchstaben-Endungen von Hausnummern ist ein gute Hinweis, und da lassen sich die meisten Fälle bestimmt mit einem Regex abdecken.

Damit sollte die Anzahl der fehlerhaften Einträge stark reduziert werden, und der Rest lässt sich ja weiterhin über die Verwaltung bearbeiten.

**Comment by ElectronicBlueberry** [comment]
Wir haben uns dagegen entschlossen Hausnummern zum Pflichtfeld zu machen, um möglichst viel Raum verschiedenste für Einträge offen zu halten.

Auf der neuen Live Seite haben wir das Adressen Feld jedoch umsortiert, und hoffen mit dass mit der neuen Reihenfolge weniger Fehler beim einreichen passieren.
