### ISSUE TITLE
Disclaimer für die Suche

### ISSUE THREAD

**Issue by Feuerhamster** [TransDB-de/projektverwaltung#10]
### Der Vorschlag

Disclaimer auf der Webseite:
> Wir können nicht für die Qualität der Angebote garantieren und sprechen keine direkten Empfehlungen aus.

### Grund für die Verbesserung

Auf Twitter haben Leute angemerkt, dass wir möglicherweise nicht empfehlenswerte oder umstrittene Angebote in unserer Suche haben. Ein allgemeiner Disclaimer würde die Nutzer darüber informieren.

**Comment by ElectronicBlueberry** [comment]
Möglicherweise als Erweiterung des Disclaimers?

**Comment by Feuerhamster** [comment]
**Ausarbeitung:** Banner auf der FAQ Seite
