### ISSUE TITLE
Zusätzliche Eingabeoption "Titel" zusätzlich zum Vor- und Nachnamen

### ISSUE THREAD

**Issue by impeira** [TransDB-de/projektverwaltung#12]
### Der Vorschlag

Im Eintrag [Hausärztliche Schwerpunktpraxis Endokrinologie/ Diabetologie/ Ernährungsmedizin](https://transdb.de/entry/61a0701ac06a180012cbc636) lautet der Name fälschlicherweise "Henri Prof. Dr. med. Wallaschofski".
Entweder sollte die Titelangabe ganz vorne stehen, der Titel woanders vermerkt werden oder der Vorname durch Komma getrennt am Ende stehen.

### Grund für die Verbesserung

Korrekte Anzeige von Namen mit Titeln.

**Comment by Feuerhamster** [comment]
Warnung: Beim Deployen muss der Text-Index für die Datenbank einmal gelöscht werden, da dieser im Code verändert wurde.

**Comment by Feuerhamster** [comment]
Eingebaut und Live
