### ISSUE TITLE
NB freundlich für Ärzt*innen und Therapeut*innen

### ISSUE THREAD

**Issue by mira-miracoli** [TransDB-de/projektverwaltung#13]
### Der Vorschlag

Ein zusätzliches Attribut "non-binary freundlich" könnte für viele hilfreich sein. Wenn Menschen die nichtbinär sind, dort gute Erfahrungen gemacht haben, können sie das so weiterempfehlen.

### Grund für die Verbesserung

Bisher nur bei Gutachter*innen. Angebote für nichtbinäre Menschen können so besser abgebildet werden.

**Comment by ElectronicBlueberry** [comment]
Ist nun auf der Live Seite vorhanden 👍
