### ISSUE TITLE
Erweiterung des Datenformats: Urologie und Gynäkologie

### ISSUE THREAD

**Issue by Feuerhamster** [TransDB-de/projektverwaltung#2]
## Der Vorschlag
Das Datenformat soll um Urologen und Gynäkologen erweitert werden.
Konkret bedeutet das:
- Neuer Types: `urologist` und `gynecologist`
- Neue Offers: `hormones`
- Neue Attributes: `transfriendly`

## Grund für die Verbesserung
Viele Personen tragen Urologen und Gynäkologen auf unserer Seite momentan noch als Endokrinologen ein.
Manche Urologen und Gynäkologen verschreiben auch Hormone und überwachen die Hormonwerte.
Deshalb ergibt es Sinn, unser Datenformat entsprechend zu erweitern.

**Comment by mira-miracoli** [comment]
Vielleicht auch hier noch ein "non-binary freundlich" Attribut.

**Comment by Feuerhamster** [comment]
Ist nun auf der Live-Seite implementiert 👍
