### ISSUE TITLE
idea: i18n support

### ISSUE THREAD

**Issue by laurafuchs** [TransDB-de/projektverwaltung#21]
### Der Vorschlag

Hello,

I've found your project and I'd like to be able to deploy it for use in a different country.

So far, most/all of the text on the website is German, and the categories are hardcoded to fit the German system.

I have my own personal fork, with changes made to the text and categories, but I think at least i18n should be implemented to make this easier.

### Grund für die Verbesserung

Makes TransDB useful outside of Germany!

**Comment by Feuerhamster** [comment]
> It's a shame, I was hoping to contribute to TransDB.
As already said, this would be possible with a specific agreement.
