### ISSUE TITLE
Datum der Einträge anzeigen

### ISSUE THREAD

**Issue by impeira** [TransDB-de/projektverwaltung#3]
Es wäre (für die Zukunft) praktisch zu wissen, wann ein Eintrag erstellt und wann dieser zuletzt aktualisiert wurde.
So kann mensch Rückschlüsse aus der Aktualität der Eintragung ziehen.

**Comment by ElectronicBlueberry** [comment]
Als tag könnte dafür `Zuletzt aktualisiert` klein in einer Ecke stehen

**Comment by ElectronicBlueberry** [comment]
Hat es nicht in den 2.0 rewrite geschafft, aber wir haben das Feature weiterhin im Auge

**Comment by Feuerhamster** [comment]
Das Feature wird für interne Zwecke hinzugefügt werden, aber nicht öffentlich einsehbar sein.
Wir haben die Befürchtung, dass die Info verwirrend sein könnte und ältere Einträge als veraltet eingeschätzt werden, obwohl das nicht stimmt.
Außerdem lässt es unsere gesamte Datenbank mit der Zeit älter aussehen.
