### ISSUE TITLE
Blacklist-Status und automatische Duplikassuche

### ISSUE THREAD

**Issue by mira-miracoli** [TransDB-de/projektverwaltung#4]
## Der Vorschlag
Blacklist und "In Entscheidung" (oder besseres Wort) Status für Einträge, Diese werden nicht öffentlich in der Suche gelistet, befinden sich aber, farblich abgehoben im Datensatz des Managements. Mithilfe einer Duplikatssuche, z.B. auf basis einzelener Wörter im Namen (tokenized), soll direkt bei den ausstehenden EInträgen ein Hinweis erscheinen, ob ein Duplikat (zusätzlich eventuell mit Blacklist Markierung) vorliegt.

## Grund für die Verbesserung
Aktuell muss jeder einzelne neue Eintrag manuell per Datenbanksuche auf Duplikate überprüft werden und eine Blacklist musste separat in einer (Google-)Tabelle (yikes!) geführt werden. Dieser Workflow hat folgende Probleme
1. deutlich länger, da jeder Blacklist eintrag manuell in der Tabelle angelegt werden muss
2. für jeden neuen Eintrag muss sowohl diese Liste durchsucht werden
3. als auch eine Duplikatsuche durchgführt werden
4. ein externes Spreadsheet ist fehleranfällig
5. das Umschalten zwischen "blacklisted, in Entscheidung und freigegeben" ist nicht möglich, die Datensätze müssen jedes mal neu hinzugefügt oder entfernt werden.

**Comment by fleaz** [comment]
Zwei Ideen dazu:
a) Blocklist statt Blacklist
b) Will man eventuell manchmal doch Einträge von der Blocklist anzeigen um bspw. vor Ärzt*Innen zu warnen bei denen bekannt ist dass man dort nicht hingehen sollte?

**Comment by mira-miracoli** [comment]
Ja genau so war mein Vorschlag gedacht, ein "Blacklisted-Status" der änderbar ist und dazu führt dass der eintrag nicht in der öffentlichen Suche angezeigt wird.
Meinst du mit Blocklist einen automatischen Filter, der zukünftige eintragungen blockt?
Ich glaube das ist technisch sehr schwer zu realisieren, da es oft einige Möglichkeiten bei der Schreibweise gibt (z.B. Dr. Korte vs. Dr. A. Korte oder Alexander Korte oder Praxis Korte usw..)
Eine automatische Duplikatssuche mit manueller entscheidung erscheint mir sicherer.

**Comment by fleaz** [comment]
Bei (a) ging es mir nur ums Wording und nicht um die technische Realisierung.

Und mit (b) meinte ich dass man Einträge von dieser Blockliste eben DOCH auf der öffentlichen Suche anzeigt halt mit nem dicken Warnlogo und ner Begründung WIESO der Eintrag auf der Blocklist gelandet ist um Menschen zu warnen das die da nicht hingehen sollen. Dafür müsste man halt im Backend dann evtl .zwei seperate Listen machen einmal für "Einträge die mit Warnmeldung im Frontend auftauchen" und "Müll, Spam und Duplikate die nicht angezeit werden"

**Comment by mira-miracoli** [comment]
Nein, ich bin ganz klar gegen eine Anzeige mit Warnung. Aus verschiedenen Gründen (s.u.) Und die technische Realisierung, die du vorschlägst scheint mir nicht zielführend. Ein Datensatz mit verschiedenen Merkmalen ist wohl deutlich leichter zu handlen als irgendwelche Duplikats, Spam und sonstige Listen. Ich sehe auch keinen Grund die zu behalten, wenn klar ist, dass sie nicht gebraucht werden.

1. Ärzte mit Warnung einzutragen ist Journalismus und kann damit als Rufschädigung betrachtet werden. Es zählt nicht mehr als Einzelmeinung. Die Abmahungen werden kommen, ich stehe im Impressum, also nein.
2. Wir möchten diese Menschen eben genau nicht promoten und ihnen Aufmerksamkeit schenken und wenn wir die Menschen nicht auf unserer Seite empfehlen möchten, sehe ich keinen Grund sie zu listen.
3. Das Projekt macht sich öffentlich dadurch angreifbar und dass meiner Ansicht nach völlig ohne Grund.

Ich würde die Diskussion um öffentliche Warnungen damit beenden.

**Comment by Feuerhamster** [comment]
Technische Ausarbeitung:
Neues Feld am Entry (nur für interne Zwecke):
Status:
- `reported`
- `observed`
- `blacklisted`

**Comment by klara-l** [comment]
Hi,

ich muss Felix beipflichten, der Begriff ist veraltet und gerade, wenn eine neue Funktionalität implementiert wird, sollten wir als Entwickler*innen nicht auf veraltete rassistische Begriffe zurückgreifen.

Ein Artikel dazu: https://www.hosteurope.de/blog/warum-heisst-die-blacklist-jetzt-blocklist-und-die-whitelist-allowlist/

**Comment by Feuerhamster** [comment]
Ist nun auf der Live-Seite implementiert 👍
