### ISSUE TITLE
Remote Attribut für Gutachter*innen und Therapeut*innen

### ISSUE THREAD

**Issue by ElectronicBlueberry** [TransDB-de/projektverwaltung#5]
## Der Vorschlag
remote bei Angeboten für Therapeut*innen und Gutachter*innen hinzufügen.

## Grund für die Verbesserung
Manche Therapeut*innen und Gutachter*innen bieten an remote zu therapieren/gutachen. Es wäre schön wenn wir dies festhalten könnten.

**Comment by Nekolumbus** [comment]
Könnte man bei Theras eigentlich auch machen

**Comment by ElectronicBlueberry** [comment]
Muss noch mal besprochen werden

**Comment by Feuerhamster** [comment]
Ist eingebaut und live
