### ISSUE TITLE
Unbekannter Fehler beim Speichern

### ISSUE THREAD

**Issue by Nekolumbus** [TransDB-de/projektverwaltung#7]
### Beschreibe das Problem

Ein unbekannter Fehler tritt auf, wenn man versucht einen bearbeiteten Eintrag abzuspeichern, aus dem man den Vor- und Nachnamen gelöscht hat.

### Schritte zur Reproduktion

1. Eintrag bearbeiten
2. Vor und Nachnahme rausnehmen
3. Speichern drücken

### In welchen Browsern tritt das Problem auf?

* Firefox 

### Auf welchen Betriebssystemen tritt das Problem auf?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by ElectronicBlueberry** [comment]
Ist in der neuen Live Version gefixed 👍
