### ISSUE TITLE
Zusätzliche Kategorie für Therapeut*innen

### ISSUE THREAD

**Issue by mira-miracoli** [TransDB-de/projektverwaltung#8]
### Der Vorschlag

Eine Kategorie "sonstige Therapeut*innen" sowie die Attribute "keine Kassenzulassung", "Kassenzulassung" (oder nur das erste).

### Grund für die Verbesserung

Es gibt neben psychologischen Psychotherapeut*innen auch welche die z.B. Gestalttherapeut*innen oder eine andere Qualifikation haben. Sie als psychologische PTs einzutragen würde falsche Qualifikationen oder die Möglichkeit mit der Kasse abzurechnen suggerieren.
Das Label "keine Kassenzulassung" wäre einhergehend damit eine wichtige Ergänzung um die Suche für viele Menschen, für die Privattherapie nicht in Frage kommt, zu vereinfachen.

**Comment by ElectronicBlueberry** [comment]
Ist jetzt auf der Live Seite vorhanden :+1:
