### ISSUE TITLE
Barrierefrei-Feld erweitern

### ISSUE THREAD

**Issue by Feuerhamster** [TransDB-de/projektverwaltung#9]
### Der Vorschlag

Das Barrierefrei-Feld im Formular um die Option "Eingeschränkt barrierefrei" oder "Teilweise barrierefrei" erweitern.

### Grund für die Verbesserung

Des häufigeren reicht Nutzern die Wahl zwischen "Barrierefrei", "Nicht Barrierefrei" oder "Unbekannt" nicht aus. Es kann vorkommen, dass ein Gebäude nur teilweise barrierefrei ist und nur bestimmte Bereiche nicht erreichbar sind.

Aus Nutzerfeedback (aus Datenschutzgründen leicht abgeändert):
> Ab wann ist ein Angebot barrierefrei? Nehmen wir mal als Beispiel: Also mit einer Gehbehinderung kommt eine Person über die Rampe rein, kann an Angeboten im großen Saal teilnehmen, eine Beratung kann auch nach unten verlegt werden. Aber zählt es bereits als barrierefrei, wenn es ein nicht erreichbares Klo gibt, sobald man ein Hilfsmittel braucht und die Treppen nach unten nicht steigen kann?

**Comment by ElectronicBlueberry** [comment]
Ich bin dagegen, weil die meisten Leute welche Einträge einreichen diese Informationen nicht wissen, und potenziell damit überfordert wären. Meine Befürchtung ist dass Leute dann ehe dazu tendieren würden die Angabe auf Unbekannt zu lassen.
